# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64 
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - 
    name: heracles
    tap:
        owner: lucagrulla
        name: homebrew-tap
    commit_author:
      name: lucagrulla
      email: luca@lucagrulla.com
    folder: Formula
    homepage: "https://github.com/lucagrulla/heracles"
    description: "Your favourite Fitbit-> Withings scale data importer"
    install: |
      bin.install "heracles"