builds:
- 
  env:
    - CGO_ENABLED=0
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - 386
    - amd64
    - arm
    - arm64 
archives:
  -
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  -
    github:
      owner: lucagrulla
      name: homebrew-tap
    commit_author:
      name: lucagrulla
      email:
    folder: Formula
    homepage: "https://github.com/lucagrulla/heracles"
    description: "Import your Fitibit Aria data to your Withings scale"
    install: |
      bin.install "heracles"
scoop:
  bucket:
    owner: lucagrulla
    name: heracles-scoop-bucket
  homepage: "https://github.com/lucagrulla/heracles"
  commit_author:
    name: lucagrulla
    email:
  description: "Import your Fitibit Aria data to your Withings scale"
  license: Apache-2.0
  persist:
    - "data"
    - "config.toml"
nfpms:
  -
    file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://www.lucagrulla.com/cw
    description: Import your Fitibit Aria data to your Withings scale
    license: Apache2
    vendor: heracles
    formats:
    - rpm
    dependencies:
    - git
    recommends:
    - rpm